<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:include filename="materials.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Base Link (Chassis) Properties -->
    <xacro:property name="base_length" value="0.3"/>
    <xacro:property name="base_width" value="0.2"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="base_mass" value="2.0"/>

    <!-- Drive Wheel Properties -->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.5"/>

    <!-- Caster Wheel Properties -->
    <xacro:property name="caster_radius" value="${wheel_radius}"/>
    <xacro:property name="caster_mass" value="${wheel_mass}"/>


    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin />
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin />
        </collision>
        <xacro:inertial_box x="${base_length}" y="${base_width}" z="${base_height}" mass="${base_mass}">
            <origin />
        </xacro:inertial_box>
    </link>

    <!-- Robot Footprint -->
    <link name="base_footprint"></link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 -${(base_height/2)+wheel_radius}"/>
    </joint>

    <!-- Left Drive Wheel -->
    <link name="drivewhl_l_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>    
            </geometry>
            <origin />
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>   
            </geometry>
            <origin />
        </collision>
        <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}" mass="${wheel_mass}">
            <origin />
        </xacro:inertial_cylinder>
    </link>

    <joint name="drivewhl_l_joint" type="continuous">
        <parent link="base_link"/>
        <child link="drivewhl_l_link"/>
        <origin xyz="-${base_length/4} ${(base_width/2)+(wheel_width/2)} -${base_height/2}" rpy="-${pi/2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <!-- Right Drive Wheel -->
    <link name="drivewhl_r_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>   
            </geometry>    
        </collision>
        <xacro:inertial_cylinder radius="${wheel_radius}" length="${wheel_width}" mass="${wheel_mass}">
            <origin />
        </xacro:inertial_cylinder>
    </link>

    <joint name="drivewhl_r_joint" type="continuous">
        <parent link="base_link"/>
        <child link="drivewhl_r_link"/>
        <origin xyz="-${base_length/4} -${(base_width/2)+(wheel_width/2)} -${base_height/2}" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 -1.0"/>
    </joint>

    <!-- Front Caster Wheel -->
    <link name="casterwhl_f_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="black"/>  
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>    
        </collision>
        <xacro:inertial_sphere radius="${caster_radius}" mass="${caster_mass}">
            <origin />
        </xacro:inertial_sphere>
    </link>

    <joint name="casterwhl_f_joint" type="fixed">
        <parent link="base_link"/>
        <child link="casterwhl_f_link"/>
        <origin xyz="${base_length/4} 0.0 -${base_height/2}"/>
    </joint>

</robot>
